#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MyApp.Resource", IsApplication=true)]

namespace MyApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::MyApp.Business.Resource.String.ApplicationName = global::MyApp.Resource.String.ApplicationName;
			global::MyApp.Business.Resource.String.Hello = global::MyApp.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05000a
			public const int LayoutCharac = 2131034122;
			
			// aapt resource value: 0x7f05000d
			public const int LayoutFooter = 2131034125;
			
			// aapt resource value: 0x7f050002
			public const int LayoutHeader = 2131034114;
			
			// aapt resource value: 0x7f05000b
			public const int gridViewCharac = 2131034123;
			
			// aapt resource value: 0x7f050008
			public const int imageButtonCharPortrait = 2131034120;
			
			// aapt resource value: 0x7f050000
			public const int linearLayout1 = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int linearLayout3 = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int linearLayout4 = 2131034113;
			
			// aapt resource value: 0x7f050009
			public const int linearLayout5 = 2131034121;
			
			// aapt resource value: 0x7f05000c
			public const int linearLayout8 = 2131034124;
			
			// aapt resource value: 0x7f050006
			public const int textViewCharClass = 2131034118;
			
			// aapt resource value: 0x7f050004
			public const int textViewCharName = 2131034116;
			
			// aapt resource value: 0x7f050007
			public const int textViewCharNiveau = 2131034119;
			
			// aapt resource value: 0x7f050005
			public const int textViewCharRace = 2131034117;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int Attack = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
